version: '1'

services:

  app:
    build:
      context: ./app
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:app/. # bind volume
    container_name: perficient-bot-backend-NodeJS
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PORT: ${PORT}