#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {model_name}-deployment
spec:
  selector:
    matchLabels:
      app: {model_name}
  replicas: 1
  template:
    metadata:
      labels:
        app: {model_name}
    spec:
      containers:
      - name: frontend
        image: docker.io/{docker_user}/{model_name}-frontend:{github.sha}
        ports:
        - containerPort: 80
      - name: backend-flask
        image: docker.io/{docker_user}/{model_name}-backend-flask:{github.sha}
        ports:
        - containerPort: 3001
      - name: backend-nodejs
        image: docker.io/{docker_user}/{model_name}-backend-nodejs:{github.sha}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {model_name}-service
  name: {model_name}-service
spec:
  ports:
  - name: frontend
    port: 80
    targetPort: 80
  - name: backend-flask
    port: 3001
    targetPort: 3001
  - name: backend-nodejs
    port: 3000
    targetPort: 3000
  selector:
    app: {model_name}
  type: LoadBalancer
